apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: basic-backend
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: basic-backend
  targetCPUUtilizationPercentage: 60